subset_of_shots: null
local: true
run_evaluation: true

input:
  data_names: &x_keys
    - [magnetics, flux_loop_flux] 
    - [magnetics, b_field_pol_probe_ccbv_field]
    - [magnetics, b_field_pol_probe_obr_field]
    - [magnetics, b_field_pol_probe_obv_field]
    - [magnetics, b_field_tor_probe_saddle_voltage]
    - [pf_active, solenoid_current]
    - [pf_active, coil_voltage]
    - [pf_active, coil_current]
    - [pulse_schedule, i_plasma]
    - [summary, power_nbi]

  target_names: &y_keys
    - [equilibrium, elongation]
    - [equilibrium, elongation_axis]
    - [equilibrium, triangularity_upper]
    - [equilibrium, triangularity_lower]
    - [equilibrium, minor_radius]
    - [equilibrium, magnetic_axis_r]
    - [equilibrium, magnetic_axis_z]
    - [equilibrium, q95]
    - [equilibrium, beta_tor]
    - [equilibrium, beta_pol]
    - [equilibrium, beta_normal]
    - [equilibrium, bvac_rmag]
    - [equilibrium, bphi_rmag]
    - [summary, ip]
    - [equilibrium, lcfs_r]
    - [equilibrium, lcfs_z]

ref_freq: 0.005

standardscaling_setting:
  # mean_path: "/metadata/2025-09-22_stdscaling/flattened_dict_mean_shot.pkl"
  # std_path: "/metadata/2025-09-22_stdscaling/flattened_dict_std_shot.pkl"
  mean_path: "/metadata/2025-09-22_stdscaling/dict_mean_shot.pkl"
  std_path: "/metadata/2025-09-22_stdscaling/dict_std_shot.pkl"

window_segmenter_setting:
  x_keys: *x_keys
  y_keys: *y_keys
  x_window_sec: 0
  y_window_sec: 0
  # dt_sec: 0
  dt_sec: 0.025
  stride_sec: null
  stride_unitary: true
  min_samples_per_window: 1
  verbose: false

cnn_model:
  D: 32

dataloader_setting:
  batch_size: 1000
  # batch_size: 500
  num_workers: 32

training:
  lr: 0.0001
  max_epochs: 500
  patience: 5

paths:
  data_split_csv_path: metadata/2025-05-12/data_splits.csv
  data_output_directory: /output/cnn_output_task_1_septembre_24/
